### ISSUE TITLE
Top app bar background color set to accent color

### ISSUE THREAD

**Issue by rabyunghwa** [material-components/material-components-android-codelabs#9]
The accent color is applied to the top app bar, which, IMHO, is wrong. What's the point of having the primary color then if it is not used at all? If the branding color is the accent color, then just make this color the primary color. Also, `AppBarLayout`'s background color defaults to `?colorPrimary`.

**Comment by cketcham** [comment]
The way color is handled by the components will be changed soon. When that happens, we will address the way colors are set for each of the components. Take a look at the "Coming Soon" section of https://material.io/develop/android/theming/color/. I'm going to close this for now since we have tickets to track this work internally. If this is still a problem when color theming is finished feel free to re-open this ticket and we will take another look.
